# Generated by Django 6.0.5 on 2026-05-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del equipo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Unitario')),
            ],
            options={
                'verbose_name': 'Activo Técnico',
                'verbose_name_plural': 'Activos Técnicos',
                'ordering': ['-id'],
            },
        ),
    ]
